#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    if [[ -f "$(dirname "$0")/gcm.help" ]]; then
        echo -e "$(cat "$(dirname "$0")/gcm.help")"
    else
        echo "Help file not found"
    fi
    exit 0
fi

if [ $# -eq 0 ]; then
    echo "Usage: gcm <commit message>"
    exit 1
fi

git commit -m "$*"

