#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    if [[ -f "$(dirname "$(dirname "$0")")/help/gbc.help" ]]; then
        echo -e "$(cat "$(dirname "$(dirname "$0")")/help/gbc.help")"
    else
        echo "Help file not found"
    fi
    exit 0
fi

git branch --show-current
